package assets;
import PipelineTools;

// generated by tiles_02.blend

class Pipeline {
	public static var sheets:Array<Sheet> = [
		new Sheet("64x64.png", 1024, 640, 0, 16, 10)
	];

	public static var tiles:Map<String, Tile> = [
		"haxeLogo" => new Tile(64, 64, 0, 0, [
			"sphereRotate" => new Anim(0, 31),
			"sphereToCubic" => new Anim(32, 63),
			"cubicRotate" => new Anim(64, 95),
			"cubicToHaxe" => new Anim(96, 146)
		]),
		"haxeCat" => new Tile(64, 64, 0, 0, [
			"default" => new Anim(147, 147)
		])
	];
}
