package assets;

// generated by chars.blend

import assets.PipelineTools.Anim;
import assets.PipelineTools.Sheet;

@:publicFields enum abstract TileID(Int) from Int to Int {
    var charactere;
    public static var names = ["charactere"];
    @:from static public function fromString(s:String):TileID return names.indexOf(s);
    public static function iterator() return new IntIterator(0,1);
}

@:publicFields enum abstract AnimID(Int) from Int to Int {
    var walk;
    public static var names = ["walk"];
    @:from static public function fromString(s:String):AnimID return names.indexOf(s);
    public static function iterator() return new IntIterator(0,1);
}

// --------- Tiles ----------

interface Tile {
    public var sheet(get, never):Int;
    public var animID:Array<AnimID>;
    public function anim(id:AnimID):Anim;
}

@:publicFields class Charactere implements Tile {
    inline function new () {};
    var sheet(get, never):Int; inline function get_sheet() return 0;
    inline function anim(id:AnimID):Anim {
        return switch(id) {
            case walk: new Anim(0, 23);
            default: throw("Error, Charactere don't have this animation"); null;
        }
    }
    var animID:Array<AnimID> = [walk];
}


class Pipeline {
    public static var sheets:Array<Sheet> = [
        new Sheet("chars64x64.png", 64, 64, 0, 8, 3),
    ];
    public inline static function tile(id:TileID):Tile {
        return switch(id) {
            case charactere: new Charactere();
            default:  throw("Error, no tile for this ID"); null;
        }
    }
}

