package assets;

// generated by 2dFun.blend

import assets.PipelineTools.Anim;
import assets.PipelineTools.Sheet;

@:publicFields enum abstract TileID(Int) from Int to Int {
    var Susi;
    public static var names = ["Susi"];
    @:from static public function fromString(s:String):TileID return names.indexOf(s);
    public static function iterator() return new IntIterator(0,1);
}

@:publicFields enum abstract AnimID(Int) from Int to Int {
    var rest;
    public static var names = ["rest"];
    @:from static public function fromString(s:String):AnimID return names.indexOf(s);
    public static function iterator() return new IntIterator(0,1);
}

// --------- Tiles ----------

interface Tile {
    public var sheet(get, never):Int;
    public var animID:Array<AnimID>;
    public function anim(id:AnimID):Anim;
}

@:publicFields class Susi implements Tile {
    inline function new () {};
    var sheet(get, never):Int; inline function get_sheet() return 0;
    inline function anim(id:AnimID):Anim {
        return switch(id) {
            case rest: new Anim(0, 0);
            default: throw("Error, Susi don't have this animation"); null;
        }
    }
    var animID:Array<AnimID> = [rest];
}


class Pipeline2D {
    public static var sheets:Array<Sheet> = [
        new Sheet("2dFun_23x23.png", 64, 64, 0, 2, 1),
    ];
    public inline static function tile(id:TileID):Tile {
        return switch(id) {
            case Susi: new Susi();
            default:  throw("Error, no tile for this ID"); null;
        }
    }
}

